version: '3'
services:
  web:
    build: 
      context: .
    environment:
      - DB_ENGINE
      - DB_NAME
      - DB_PASSWORD
      - DB_USER
      - DB_HOST
      - DB_PORT
    ports:
    - "8000:8000"
 
